# Bind address
bind.addr=localhost:8080

# MongoDB connection URL
mongodb.url=mongodb://localhost:27017/database

# StatsD configuration
statsd.host=localhost
statsd.port=8125

# Namespace for the application
application.namespace=postcode-lookup
